// Copyright (c) 2026 Ali Rashid. Licensed under the Apache License, Version 2.0.
// See LICENSE in the project root for licence information.

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Lugha.Generators;

/// <summary>
/// Emits a <c>partial class LocaleManifest</c> with:
/// <list type="bullet">
///   <item><c>Scopes</c> - all <c>ITextScope</c> interface names.</item>
///   <item><c>Locales</c> - all concrete <c>ILocale</c> class names.</item>
///   <item><c>MemberCount&lt;TScope&gt;()</c> - member count per scope.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LocaleManifestGenerator : IIncrementalGenerator
{
  /// <inheritdoc />
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Collect all type declarations.
    IncrementalValuesProvider<TypeDeclarationSyntax> typeDeclarations =
        context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => (TypeDeclarationSyntax)ctx.Node);

    IncrementalValueProvider<(Compilation Compilation, ImmutableArray<TypeDeclarationSyntax> Types)> combined =
        context.CompilationProvider.Combine(typeDeclarations.Collect());

    context.RegisterSourceOutput(combined, static (spc, source) =>
    {
      (Compilation compilation, ImmutableArray<TypeDeclarationSyntax> types) = source;
      Execute(compilation, types, spc);
    });
  }

  private static void Execute(
      Compilation compilation,
      ImmutableArray<TypeDeclarationSyntax> typeDeclarations,
      SourceProductionContext context)
  {
    INamedTypeSymbol? textScopeSymbol = compilation.GetTypeByMetadataName(GeneratorTextScopeHelper.TextScopeFullName);
    if (textScopeSymbol is null)
    {
      return;
    }

    var scopes = new List<(string Name, string FullName, int MemberCount)>();
    var locales = new List<string>();
    var processedTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

    foreach (TypeDeclarationSyntax typeDecl in typeDeclarations)
    {
      SemanticModel model = compilation.GetSemanticModel(typeDecl.SyntaxTree);
      if (model.GetDeclaredSymbol(typeDecl, context.CancellationToken) is not INamedTypeSymbol typeSymbol)
      {
        continue;
      }

      if (!processedTypes.Add(typeSymbol))
      {
        continue;
      }

      // Collect text scope interfaces.
      if (GeneratorTextScopeHelper.IsTextScopeInterface(typeSymbol))
      {
        int memberCount = typeSymbol.GetMembers()
            .Count(m => !m.IsImplicitlyDeclared && m is IPropertySymbol or IMethodSymbol { MethodKind: MethodKind.Ordinary });
        scopes.Add((typeSymbol.Name, typeSymbol.ToDisplayString(), memberCount));
      }

      // Collect concrete ILocale classes.
      if (typeSymbol.TypeKind is TypeKind.Class &&
          !typeSymbol.IsAbstract &&
          GeneratorTextScopeHelper.ImplementsLocale(typeSymbol))
      {
        locales.Add(typeSymbol.Name);
      }
    }

    if (scopes.Count == 0 && locales.Count == 0)
    {
      return;
    }

    scopes.Sort((a, b) => string.CompareOrdinal(a.Name, b.Name));
    locales.Sort(string.CompareOrdinal);

    string source = GenerateManifestSource(scopes, locales);
    context.AddSource("LocaleManifest.g.cs", source);
  }

  private static string GenerateManifestSource(
      List<(string Name, string FullName, int MemberCount)> scopes,
      List<string> locales)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated />");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using System;");
    sb.AppendLine();
    sb.AppendLine("/// <summary>");
    sb.AppendLine("/// Auto-generated locale manifest providing compile-time metadata about");
    sb.AppendLine("/// text scopes and locale implementations in this assembly.");
    sb.AppendLine("/// </summary>");
    sb.AppendLine("public static partial class LocaleManifest");
    sb.AppendLine("{");

    // Scopes property.
    sb.AppendLine("    /// <summary>All ITextScope-derived interface names.</summary>");
    sb.Append("    public static string[] Scopes => [");
    for (int i = 0; i < scopes.Count; i++)
    {
      if (i > 0)
      {
        sb.Append(", ");
      }

      sb.Append('"').Append(scopes[i].Name).Append('"');
    }

    sb.AppendLine("];");
    sb.AppendLine();

    // Locales property.
    sb.AppendLine("    /// <summary>All concrete ILocale class names.</summary>");
    sb.Append("    public static string[] Locales => [");
    for (int i = 0; i < locales.Count; i++)
    {
      if (i > 0)
      {
        sb.Append(", ");
      }

      sb.Append('"').Append(locales[i]).Append('"');
    }

    sb.AppendLine("];");
    sb.AppendLine();

    // MemberCount<TScope>() method.
    sb.AppendLine("    /// <summary>Returns the member count for the specified text scope type.</summary>");
    sb.AppendLine("    public static int MemberCount<TScope>() where TScope : Lugha.ITextScope =>");
    if (scopes.Count > 0)
    {
      sb.AppendLine("        typeof(TScope) switch");
      sb.AppendLine("        {");
      foreach ((string _, string fullName, int memberCount) in scopes)
      {
        sb.AppendLine($"            _ when typeof(TScope) == typeof({fullName}) => {memberCount},");
      }

      sb.AppendLine("            _ => 0,");
      sb.AppendLine("        };");
    }
    else
    {
      sb.AppendLine("        0;");
    }

    sb.AppendLine("}");

    return sb.ToString();
  }
}
