// Copyright (c) 2026 Ali Rashid. Licensed under the Apache License, Version 2.0.
// See LICENSE in the project root for licence information.

using System.Text;
using Lugha.Common;

namespace Lugha.Import;

/// <summary>
/// Emits C# source code from parsed translation sets.
/// </summary>
/// <remarks>
/// <para>Two emission modes:</para>
/// <list type="bullet">
///   <item><b>Contract emission</b> - from a single "reference" locale
///     (typically the source language), emit <c>ITextScope</c> interfaces.
///     Properties for invariant strings, methods for parameterised strings.</item>
///   <item><b>Implementation emission</b> - from each locale's
///     <see cref="TranslationSet"/>, emit a sealed class implementing
///     the corresponding <c>ITextScope</c> interface.</item>
/// </list>
/// <para>
/// The emitted code participates in normal Lugha compilation.
/// Missing translations cause compile errors (interface member not implemented).
/// Extra translations cause compile errors (member does not exist on interface).
/// Parameter mismatches cause compile errors (signature mismatch).
/// </para>
/// </remarks>
public static class CodeEmitter
{
  /// <summary>
  /// Emits <c>ITextScope</c> interface declarations from a reference locale.
  /// </summary>
  /// <param name="reference">The source-language translation set.</param>
  /// <param name="targetNamespace">Namespace for emitted interfaces.</param>
  /// <returns>C# source text for each generated interface file.</returns>
  public static IReadOnlyList<EmittedFile> EmitContracts(
      TranslationSet reference,
      string targetNamespace)
  {
    Dictionary<string, List<TranslationEntry>> scopes = GroupByScope(reference.Entries);
    var files = new List<EmittedFile>(scopes.Count);

    foreach (KeyValuePair<string, List<TranslationEntry>> kvp in scopes)
    {
      string scopeName = kvp.Key;
      List<TranslationEntry> entries = kvp.Value;
      string interfaceName = ToInterfaceName(scopeName);
      var sb = new StringBuilder();

      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine();
      sb.AppendLine("using Lugha;");
      sb.AppendLine();
      sb.Append("namespace ").Append(targetNamespace).AppendLine(";");
      sb.AppendLine();
      sb.Append("public interface ").Append(interfaceName).AppendLine(" : ITextScope");
      sb.AppendLine("{");

      foreach (TranslationEntry entry in entries)
      {
        string memberName = ExtractMemberName(entry.Key);

        if (entry.Parameters.Count == 0)
        {
          sb.Append("    string ").Append(memberName).AppendLine(" { get; }");
        }
        else
        {
          sb.Append("    string ").Append(memberName).Append('(');
          AppendParameterList(sb, entry.Parameters);
          sb.AppendLine(");");
        }
      }

      sb.AppendLine("}");

      files.Add(new EmittedFile($"{interfaceName}.g.cs", sb.ToString()));
    }

    return files;
  }

  /// <summary>
  /// Emits a sealed class implementing each <c>ITextScope</c> for
  /// a specific locale.
  /// </summary>
  /// <param name="locale">The locale's translation set.</param>
  /// <param name="contractNamespace">
  ///   Namespace containing the <c>ITextScope</c> interfaces
  ///   (from <see cref="EmitContracts"/>).
  /// </param>
  /// <param name="targetNamespace">Namespace for emitted implementations.</param>
  /// <returns>C# source text for each generated implementation file.</returns>
  public static IReadOnlyList<EmittedFile> EmitImplementations(
      TranslationSet locale,
      string contractNamespace,
      string targetNamespace)
  {
    Dictionary<string, List<TranslationEntry>> scopes = GroupByScope(locale.Entries);
    var files = new List<EmittedFile>(scopes.Count);
    string classPrefix = ToClassPrefix(locale.Language);

    // Extract the base language tag for rule resolution (e.g. "es-ES" -> "es")
    string baseLanguage = ExtractBaseLanguage(locale.Language);
    RulePair? rulePair = LanguageRules.Resolve(baseLanguage);

    // Also try the full tag if base didn't resolve (e.g. "pt-PT")
    rulePair ??= LanguageRules.Resolve(locale.Language);

    foreach (KeyValuePair<string, List<TranslationEntry>> kvp in scopes)
    {
      string scopeName = kvp.Key;
      List<TranslationEntry> entries = kvp.Value;
      string interfaceName = ToInterfaceName(scopeName);
      string className = classPrefix + scopeName + "Text";
      bool scopeHasPlurals = HasPluralEntries(entries);
      var sb = new StringBuilder();

      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine();

      if (scopeHasPlurals)
      {
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using Lugha;");
        if (rulePair is not null)
        {
          sb.AppendLine("using Lugha.Rules.Cardinals;");
        }
      }

      if (contractNamespace != targetNamespace)
      {
        sb.Append("using ").Append(contractNamespace).AppendLine(";");
      }

      sb.AppendLine();
      sb.Append("namespace ").Append(targetNamespace).AppendLine(";");
      sb.AppendLine();
      sb.Append("public sealed class ").Append(className).Append(" : ").AppendLine(interfaceName);
      sb.AppendLine("{");

      if (scopeHasPlurals)
      {
        sb.Append("    private static readonly CultureInfo Culture = CultureInfo.GetCultureInfo(\"")
          .Append(locale.Language)
          .AppendLine("\");");
        sb.AppendLine();
      }

      for (int i = 0; i < entries.Count; i++)
      {
        TranslationEntry entry = entries[i];
        string memberName = ExtractMemberName(entry.Key);

        if (entry.PluralForms is not null && entry.PluralForms.Count > 0 && rulePair is not null)
        {
          EmitPluralMember(sb, memberName, entry, rulePair.Value);
        }
        else if (entry.Parameters.Count == 0)
        {
          sb.Append("    public string ").Append(memberName).Append(" => \"")
            .Append(EscapeStringLiteral(entry.Value))
            .AppendLine("\";");
        }
        else
        {
          sb.Append("    public string ").Append(memberName).Append('(');
          AppendParameterList(sb, entry.Parameters);
          sb.Append(") => $\"");
          sb.Append(ToInterpolatedString(entry.Value));
          sb.AppendLine("\";");
        }

        if (i < entries.Count - 1)
        {
          sb.AppendLine();
        }
      }

      sb.AppendLine("}");

      files.Add(new EmittedFile($"{className}.g.cs", sb.ToString()));
    }

    return files;
  }

  /// <summary>
  /// Derives the <c>ITextScope</c> interface name from a scope name.
  /// E.g. <c>"Connection"</c> -> <c>"IConnectionText"</c>.
  /// </summary>
  /// <param name="scopeName">The scope name extracted from the key's first segment.</param>
  /// <returns>The interface name.</returns>
  public static string ToInterfaceName(string scopeName) =>
      "I" + scopeName + "Text";

  /// <summary>
  /// Derives the implementation class name prefix from a BCP 47 language tag.
  /// E.g. <c>"es-ES"</c> -> <c>"EsEs"</c>, <c>"en"</c> -> <c>"En"</c>.
  /// </summary>
  /// <param name="languageTag">The BCP 47 language tag.</param>
  /// <returns>PascalCased prefix for class names.</returns>
  public static string ToClassPrefix(string languageTag)
  {
    var sb = new StringBuilder(languageTag.Length);
    bool capitaliseNext = true;

    for (int i = 0; i < languageTag.Length; i++)
    {
      char c = languageTag[i];

      if (c is '-' or '_')
      {
        capitaliseNext = true;
        continue;
      }

      sb.Append(capitaliseNext ? char.ToUpperInvariant(c) : char.ToLowerInvariant(c));
      capitaliseNext = false;
    }

    return sb.ToString();
  }

  private static string ExtractBaseLanguage(string languageTag)
  {
#if NET10_0_OR_GREATER
        int dashIndex = languageTag.IndexOf('-', StringComparison.Ordinal);
#else
    int dashIndex = languageTag.IndexOf('-');
#endif
    return dashIndex >= 0 ? languageTag[..dashIndex] : languageTag;
  }

  private static string ExtractMemberName(string key)
  {
#if NET10_0_OR_GREATER
        int dotIndex = key.IndexOf('.', StringComparison.Ordinal);
#else
    int dotIndex = key.IndexOf('.');
#endif
    return dotIndex >= 0 ? key[(dotIndex + 1)..] : key;
  }

  private static string ExtractScopeName(string key)
  {
#if NET10_0_OR_GREATER
        int dotIndex = key.IndexOf('.', StringComparison.Ordinal);
#else
    int dotIndex = key.IndexOf('.');
#endif
    return dotIndex >= 0 ? key[..dotIndex] : key;
  }

  private static Dictionary<string, List<TranslationEntry>> GroupByScope(
      IReadOnlyList<TranslationEntry> entries)
  {
    Dictionary<string, List<TranslationEntry>> scopes = [];

    foreach (TranslationEntry entry in entries)
    {
      string scopeName = ExtractScopeName(entry.Key);

      if (!scopes.TryGetValue(scopeName, out List<TranslationEntry>? list))
      {
        list = [];
        scopes[scopeName] = list;
      }

      list.Add(entry);
    }

    return scopes;
  }

  private static void AppendParameterList(StringBuilder sb, IReadOnlyList<string> parameters)
  {
    for (int i = 0; i < parameters.Count; i++)
    {
      if (i > 0)
      {
        sb.Append(", ");
      }

      // Parameters named "count" get int type; all others get string
      string paramName = parameters[i];
      string paramType = paramName is "count" ? "int" : "string";
      sb.Append(paramType).Append(' ').Append(paramName);
    }
  }

  private static void EmitPluralMember(
      StringBuilder sb,
      string memberName,
      TranslationEntry entry,
      RulePair rulePair)
  {
    sb.Append("    public string ").Append(memberName).Append('(');
    AppendParameterList(sb, entry.Parameters);
    sb.AppendLine(") =>");
    sb.Append("        $\"{count.ToString(\"N0\", Culture)} {Plural.Select<")
      .Append(rulePair.Cardinal)
      .AppendLine(">(count, new PluralForms");
    sb.AppendLine("        {");

    foreach (KeyValuePair<string, string> kvp in entry.PluralForms!)
    {
      string categoryName = char.ToUpperInvariant(kvp.Key[0]) + kvp.Key[1..];
      sb.Append("            ").Append(categoryName).Append(" = \"")
        .Append(EscapeStringLiteral(kvp.Value))
        .AppendLine("\",");
    }

    sb.AppendLine("        })}\";");
  }

  private static string EscapeStringLiteral(string value) =>
      value
#if NET10_0_OR_GREATER
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
#else
          .Replace("\\", "\\\\")
          .Replace("\"", "\\\"")
          .Replace("\n", "\\n")
          .Replace("\r", "\\r")
          .Replace("\t", "\\t");
#endif

  private static string ToInterpolatedString(string value) =>
      value
#if NET10_0_OR_GREATER
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
#else
          .Replace("\\", "\\\\")
          .Replace("\"", "\\\"")
          .Replace("\n", "\\n")
          .Replace("\r", "\\r")
          .Replace("\t", "\\t");
#endif

  private static bool HasPluralEntries(List<TranslationEntry> entries)
  {
    foreach (TranslationEntry entry in entries)
    {
      if (entry.PluralForms is not null && entry.PluralForms.Count > 0)
      {
        return true;
      }
    }

    return false;
  }
}
